### ISSUE TITLE
Color names are inaccurate / incomplete

### ISSUE THREAD

**Issue by fidwell** [Manticore-007/OpenRCT2-PeepEditor#12]
**Describe the bug**
Some of the colors in the color picker do not have the same name listed in the text box after being selected (for example, "Dark water" is listed as "Teal").

The new colors all come back as "undefined" instead of whatever their name is.

**Screenshots**
![image](https://github.com/Manticore-007/OpenRCT2-PeepEditor/assets/5436387/71b16a3b-7f7c-4d03-99ff-36ac5a69e7c9)
![image](https://github.com/Manticore-007/OpenRCT2-PeepEditor/assets/5436387/97105324-743c-43c1-88cc-dc749c71fc3e)

**Comment by Manticore-007** [comment]
Fixed in commit f6c42db
