### ISSUE TITLE
Unable to Change Staff Member's Costume

### ISSUE THREAD

**Issue by jkhero73** [Manticore-007/OpenRCT2-PeepEditor#15]
**Bug Description**
When attempting to change a staff member's costume, an error message reading "Unknown Unknown" appears, and the costume does not change. Entertainers can change to the default guest costume and other entertainer costumes, but no others.

**Steps To Reproduce**
1. Install the current release of PeepEditor into the latest dev build of OpenRCT2.
2. Create or Load a save.
3. Use Peep Editor to select any staff member.
4. Attempt to change their costume. Any will do.
5. View error message and observe lack of changed costume.

**Expected Behavior**
The staff member should change their appearance to match the selected costume, and no error message should appear.

**Screenshots**
![image](https://github.com/user-attachments/assets/51291eab-4310-4a84-af6b-4b09e0417a92)
![image](https://github.com/user-attachments/assets/cec4ef7b-9bf0-41e5-9f49-4d36c1066c2e)

**Comment by Manticore-007** [comment]
First of all, apologies for the late response.

I am working on a new version that is compatible with the latest develop, I shared it on several Discords when there were breaking changes. But recently I released a beta version here, so there is a compatible version. Keep in mind, not all functionality is there. You can find it here:

https://github.com/Manticore-007/OpenRCT2-PeepEditor/releases/tag/v24.7.7-beta
