### ISSUE TITLE
Freezing staff member only slow them down

### ISSUE THREAD

**Issue by Vetador** [Manticore-007/OpenRCT2-PeepEditor#16]
**Describe the bug**
I click "select a peep to modify it" and then I click on "freeze peep" but he simply walk slower and I can't "unfreeze it" by clicking again.

**To reproduce**
1. Go to 'peep editor'
2. Click on 'select peep to modify it'
3. Select an entertainer peep.
4. CLick on 'freeze peep'
5. See problem

Note: I try to lower the speed manually but the minimum speed is set to 32.

**Expected behavior**
I expected the entertainer peep to froze completely.

**Comment by Manticore-007** [comment]
~~Which version are you using, or can you add a screenshot of the Peep Editor?~~

Edit: someone had the same problem and it was the old version. Please download the following to solve the issue for now:
https://github.com/Manticore-007/OpenRCT2-PeepEditor/releases/tag/v24.7.7-beta
